#+TITLE: The current angst
#+AUTHOR: Thirumal Ravula
#+DATE: [2018-09-02 Sun]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Essay
  This is a note about the rising angst among the majority
  of Indians; the people who are trying to provide answers
  to that helplessness; and the state trying to suppress any
  notion of dissent.

  The current angst is not really a about the right taking
  over left, or the brahmnism trying to assert over dalit
  bahujans, that has been happening all the time in India.

  To be fair the left is very negligible in India, the left
  and the center in India from Independence established a
  Nehruvian populist bourgeois capitalist state.

  Except that there always were organic movements and
  organic leaders in the hue of Bhagat Singh, T Nagi Reddy
  etc.

  But there is also this people whose current practise of
  perpetuating the same bourgeois state is no different from
  the earlier party, but wanted power , their ideology might
  say something like economic nationalism but their hue and
  cry and the noises of hindutva are only a cover for the
  power, like pseudo secularism to the other side.

  All the current political parties are in the grip of
  Indian version of Koch brothers. 

  Today I see the real fight will be between the people who
  want a just society that is equitable and sustainable and
  the others that favors the self over the community.

  So, therefore every 'brahmin' ( I mean in the real sense
  that all teachers are ), should think over this and form a
  solidarity to lead from the just side.

  This is not just a moral calling but an existential one.

