#+TITLE: Reflections on Ajanta Caves
#+AUTHOR: Thirumal Ravula
#+DATE: [2021-10-14 Thu]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


Equality of Life, one would discern from the incessant cycle
of birth, growing up and followed by death of every living
being.  When this is the pattern of life, what I understand
from Buddhist inquiry is to perceive the banality of such a
cycle.  Such a perspective allows one to reorient the
current life in understanding the workings of that
particular life set within the context of this larger canvas
of universe, where every life is determined by the same
cycle.  Since man is endowed by the mind, that allows one to
reflect and seek the truth, probably compassion emanates for
every other life from this simple reflection.  Self
preservation entails a great many superfluous activities and
feelings that from a purely individualistic prism contain a
great import.  But the scaffolding of such an edifice starts
to shift when one starts to realize it as a pattern of
life - birth, growing up and death.  Such a reflection
allowed the bikhus to reorient their pursuit of life on a
different path.  The meditation - a form of self
reflection - conjured these stupendous marvels at the Ajanta
Caves.  The chiselling away of rock to bring forth
craftsmanship that is unparalleled is not an end in itself
but a means to overcome the limitations of self trapped in a
body.  This entrapment with all its encumbrances that
emanate from the material interactions is the mire that one
needs to get hold of, understand and work one's way to
unleash a greater potential that lay within us - simply to
understand this cycle of life that pervades every form of
life.  When such is the pursuit, what comes out of the
effort will only be a marvel.  Work or human endeavor of
these bikhus - who chose a lifestyle that gave preponderance
to initiate a start in the direction where one ultimately
merges with the whole - is defined by the pursuit of
perfection and its result inspires an awe.  At any moment in
our life, we are seemingly circumscribed by the elements of
nature - time and space - that in turn parameterize our base
nature.  Therefore it is pertinent to realize the structure
of their understanding to enable the carving of these
magnificent structures.

