* A Case study - Rural Stays
  Rural stays is an harbinger to build alternate forms of
  organization.  A platform that allows offering of services
  in a transparent and federated way.  Rural India offers a
  bounty of opportunities to unwind for a city dweller.  The
  village is mostly unpolluted, there are myriad productive
  activities to engage in.  One could go on a trek with
  shepherds, or participate in the harvest of crop during a
  season not in any contrived fashion but as it exists.  Or
  one could just breathe fresh air and relax.  The Rural
  stays provides the right infrastructure to connect people
  who support to undertake these activities and the guests
  who participate in these activities.

  


The concepts of software, as little
  functions coming together to perform a bigger task, whose
  behaviours determine that particular system contained with
  a certain set.  Applied this concept to society, implies
  municipalization of utilities, democratization of energy
  grids, cooperatives of consumers and producers - all
  systems that show the properties of agglomeration to
  perform a service while retaining the same properties of
  the blocks that comprise a bigger system.

  Does cooperation provide us with a system that is more
  optimized - that achieve stated goals with minimal
  resources? Or even given a chance of defining those goals,
  how does it fare in achieving them.  Any system that can
  plug in with their own set of rules but all the while
  scaffolded on a set of basic principles that can be
  specified and are attuned to solve some of the problems
  generated by the current system of organizations.  The
  ability to model the current system and compare it with a
  cooperative model provide us with insights that are used
  to alter the specifications of the desired system.

  Another way is to build real systems.  Take for example a
  cooperative transport system.  The objectives of the
  system are:
  1. Reduce the number of vehicles on the road.
  2. Provide the convenience of transport to everyone with
     shared transport as the primary medium.
  3. Rules and the actual act of resource generation and
     service provision are federated, transparent and
     democratic.

  How does this model contrast with the current system?
  Where do we begin to list the characteristics of the
  current system? Can we equate to a capitalist system where
  market is the ultimate optimizer?  What does this model
  offer us and how do we feed to the desired model?

  Where do I begin to understand the characteristics of the
  desired system?  A model that rewards the people whose
  socially equal labor induces the commodities over another
  one that allows capital with market acting as a feedback
  to dictate the terms of rewards.

  What is a just society?  When I have the ability to lay on
  my back anywhere, with a beauty and without any pollution.
  What is the logical way to achieve this? The idea of
  Soviet that I learned from Nishad Patnaik, is based on
  rational thought.  The idea that a rational system with
  inner logic can be used to build social movements and
  social structures is paramount.  Using such soviets as
  building blocks, can a model allow anyone in a modern
  world an afternoon siesta in the open.

  While we build this model, the history of cooperatives,
  will feed into it to strengthen the logic of being on the
  path towards an end.  What is the sole motivation of labor
  unions?  The resistance that is offered to the commodity
  makers is the inherent contradiction of capitalism.  The
  income deflation at the heart of capitalism induces demand
  deflation; it is like shooting themselves in the chase for
  profit.  Though the system tries to act as Sui generis,
  but forgets the people it is exploiting.  It exhibits a
  flawed way of cooperation, because of the lack of
  self-conception of cooperation.

  Similarly, in a world of soviets, if we claim that we can
  reason about it, why did structures of exploitation arise?
  How do we factor these aberrations into the system.  The
  claim of part-whole logic fits well into a discipline like
  computer science.  But when applied to social
  organizations with vast social structures, it throws up
  limitations.  One such limitation is envisaging the whole,
  while part of it.  Though the parts have their
  characteristics, the same are influenced by the whole.
  But the whole is always in a transition with internal
  movements whose direction and influence is hard to fathom
  before the effects are in bloom.  

  The limitations of the mechanical analogy forces us to
  acknowledge the existence of a current system; and the
  evolution of a new system works within the current system
  but also have the ability to affect such systems.

  A realization of such a cooperating system is an open
  transport system.  The fundamental characteristic of this
  is agglomeration via organization as a democratic
  federation.  It ensures systems that exhibit a similar
  trait can also flourish along side undemocratic structures
  which is the reality.  As a software what are the
  challenges that confront while building it.  The challenge
  is not really envisaging the software system as a service
  but more about providing the ability to configure
  behaviours.  How does the system encourage choosing
  services that have an intended purpose that lean towards
  our stated goal.
