#+TITLE: Musings
#+AUTHOR: Thirumal Ravula
#+DATE: [2016-12-25 Sun]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction
  These are some of my jottings which I do rarely but of late want to do more
  often.

* [[./papers/index.org][Stating the problem for Phd]].
  I see a potential for computation in understanding our
  society in terms of our economic, political and social
  organizations and how we can draw the insights from such
  models to help restructure them for a equitable and
  sustainable society.  [[./papers/index.org][Index]] to different write ups on
  articulating the problem.

* Coop Services
  One of the solutions for a sustainable and equitable world
  is worker ownership.  Cooperatives are the ideal solution
  in that direction.  How does the new tools of computations
  and information flow allow to build such worker owned
  cooperatives?
** [[./insights/index.org][First Insight]]
** [[./insights/more-insights.org][More Insights]]
* [[./trips/index.org][Trips]]
  Index to [[./trips/index.org][trips]]

* [[./social/index.org][Our Current Society]]
  [[./social/index.org][Perspectives]] on where we are headed
* Kissan Cooperative
  
  [[./kissan-coop/index.org][Memo for a Kissan Cooperative]]

* Notes
  [[./notes/index.org][Index]] to notes.
* About Me
  [[./about/index.org][Index]] to who I am.
